// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Platform.Infrastructure.Persistence;

#nullable disable

namespace Platform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260426134631_DocumentMemoryV1")]
    partial class DocumentMemoryV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Domain.Features.Dashboard.StatsSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatsSnapshots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Json = "{\"tiles\":[{\"label\":\"Sessions Completed\",\"value\":24,\"unit\":\"\",\"color\":\"var(--accent)\",\"sub\":\"+3 this week\"},{\"label\":\"Articles Read\",\"value\":187,\"unit\":\"\",\"color\":\"var(--accent)\",\"sub\":\"+12 this week\"},{\"label\":\"Saved Items\",\"value\":43,\"unit\":\"\",\"color\":\"rgba(232,237,248,0.45)\",\"sub\":\"5 added recently\"},{\"label\":\"Day Streak\",\"value\":12,\"unit\":\"d\",\"color\":\"#34d399\",\"sub\":\"Personal best: 18d\"},{\"label\":\"Avg Session Length\",\"value\":38,\"unit\":\"min\",\"color\":\"var(--accent)\",\"sub\":\"Target: 45 min\"},{\"label\":\"Topics Explored\",\"value\":9,\"unit\":\"\",\"color\":\"#a78bfa\",\"sub\":\"3 in progress\"},{\"label\":\"Knowledge Score\",\"value\":94,\"unit\":\"%\",\"color\":\"#34d399\",\"sub\":\"Top 8% of users\"},{\"label\":\"Hours Learned\",\"value\":41,\"unit\":\"h\",\"color\":\"#fbbf24\",\"sub\":\"This month\"}],\"progress\":[{\"label\":\"Weekly Learning Goal\",\"value\":68,\"color\":\"var(--accent)\"},{\"label\":\"AI Ethics Mastery\",\"value\":82,\"color\":\"var(--accent)\"},{\"label\":\"Reading Streak\",\"value\":45,\"color\":\"#34d399\"},{\"label\":\"Profile Completion\",\"value\":91,\"color\":\"#a78bfa\"}],\"activity\":[{\"day\":\"Mon\",\"sessions\":2},{\"day\":\"Tue\",\"sessions\":1},{\"day\":\"Wed\",\"sessions\":3},{\"day\":\"Thu\",\"sessions\":0},{\"day\":\"Fri\",\"sessions\":2},{\"day\":\"Sat\",\"sessions\":1},{\"day\":\"Sun\",\"sessions\":2}]}"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.HumanInput.InputNeededItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Urgent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("InputNeededItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "How would you rate the difficulty and quality of your last session? This helps calibrate future recommendations.",
                            Text = "Rate your last AI Ethics session",
                            Type = "Rating",
                            Urgent = true
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Detected reading patterns suggesting interest in Quantum Computing. Add it to your interest profile?",
                            Text = "Confirm new interest: Quantum Computing?",
                            Type = "Confirm",
                            Urgent = false
                        },
                        new
                        {
                            Id = 3,
                            Detail = "You have completed your current track. Select a new area to explore from your recommended topics.",
                            Text = "Choose your next learning topic",
                            Type = "Choose",
                            Urgent = false
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.ExplicitUserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveProjectsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("AuthorityWeight")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<string>>("CoreInterests")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Goals")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<string>>("SecondaryInterests")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SkillLevelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("memory_explicit_profile", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryConsolidationRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AutoUpdatesCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ProcessedEventsCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalsCreatedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_memory_consolidation_runs_idempotency_key");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_memory_consolidation_runs_user_started");

                    b.ToTable("memory_consolidation_runs", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryEmbedding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddedText")
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<string>("EmbeddingModelKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmbeddingModelVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("MemoryItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MemoryItemId");

                    b.HasIndex("UserId", "MemoryItemId", "EmbeddingModelKey", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_memory_embeddings_user_item_model_chunk");

                    b.ToTable("memory_embeddings", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_memory_events_user_id");

                    b.HasIndex("UserId", "EventType")
                        .HasDatabaseName("ix_memory_events_user_id_event_type");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("ix_memory_events_user_id_occurred_at");

                    b.ToTable("memory_events", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryEvidence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("SemanticMemoryId")
                        .HasColumnType("bigint");

                    b.Property<double>("Strength")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_memory_evidence_event_id");

                    b.HasIndex("SemanticMemoryId")
                        .HasDatabaseName("ix_memory_evidence_semantic_memory_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_memory_evidence_user_id");

                    b.HasIndex("UserId", "SemanticMemoryId")
                        .HasDatabaseName("ix_memory_evidence_user_semantic");

                    b.ToTable("memory_evidence", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AuthorityWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double>("FreshnessScore")
                        .HasColumnType("double precision");

                    b.Property<double>("Importance")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemoryType")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StructuredJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_memory_items_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_memory_items_user_id");

                    b.HasIndex("UserId", "Domain")
                        .HasDatabaseName("ix_memory_items_user_id_domain");

                    b.HasIndex("UserId", "MemoryType")
                        .HasDatabaseName("ix_memory_items_user_id_memory_type");

                    b.HasIndex("UserId", "ProjectId")
                        .HasDatabaseName("ix_memory_items_user_id_project_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_memory_items_user_id_status");

                    b.ToTable("memory_items", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryRelationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromEntity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("Strength")
                        .HasColumnType("double precision");

                    b.Property<string>("ToEntity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FromEntity")
                        .HasDatabaseName("ix_memory_relationships_user_id_from");

                    b.HasIndex("UserId", "RelationType")
                        .HasDatabaseName("ix_memory_relationships_user_id_relation_type");

                    b.HasIndex("UserId", "ToEntity")
                        .HasDatabaseName("ix_memory_relationships_user_id_to");

                    b.ToTable("memory_relationships", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryReviewQueueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApprovedProceduralRuleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApprovedSemanticMemoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("ProposalType")
                        .HasColumnType("integer");

                    b.Property<string>("ProposedChangeJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedProceduralRuleId");

                    b.HasIndex("ApprovedSemanticMemoryId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_memory_review_queue_created_at");

                    b.HasIndex("UserId", "Status", "Priority")
                        .HasDatabaseName("ix_memory_review_queue_user_id_status_priority");

                    b.ToTable("memory_review_queue", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("memory_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.ProceduralRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AuthorityWeight")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RuleContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WorkflowType", "Status")
                        .HasDatabaseName("ix_procedural_rules_user_workflow_status");

                    b.HasIndex("UserId", "WorkflowType", "RuleName", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_procedural_rules_user_rule_name_version");

                    b.ToTable("procedural_rules", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.SemanticMemory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AuthorityWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LastSupportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_semantic_memories_user_id");

                    b.HasIndex("UserId", "Key")
                        .HasDatabaseName("ix_semantic_memories_user_id_key");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_semantic_memories_user_id_status");

                    b.ToTable("semantic_memories", (string)null);
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.MemoryInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MemoryInsights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Confirmed = true,
                            Content = "You consistently engage with AI governance and regulation content over the past 6 weeks.",
                            Label = "Recurring Interest",
                            Strength = 94
                        },
                        new
                        {
                            Id = 2,
                            Confirmed = true,
                            Content = "You prefer structured sessions under 60 minutes, with hands-on exercises.",
                            Label = "Learning Pattern",
                            Strength = 87
                        },
                        new
                        {
                            Id = 3,
                            Confirmed = false,
                            Content = "Your reading behavior suggests growing interest in hardware-level AI acceleration.",
                            Label = "Emerging Trend",
                            Strength = 61
                        },
                        new
                        {
                            Id = 4,
                            Confirmed = false,
                            Content = "Foundational probability and statistics appear underrepresented in your learning history.",
                            Label = "Knowledge Gap",
                            Strength = 78
                        },
                        new
                        {
                            Id = 5,
                            Confirmed = false,
                            Content = "Based on your interests, a learning path toward AI Safety Research would match your profile well.",
                            Label = "Recommended Path",
                            Strength = 82
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.News.NewsItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("NewsItems");

                    b.HasData(
                        new
                        {
                            Id = "n1",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 4, 2, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Source = "Wire",
                            Title = "Sample headline (placeholder)"
                        },
                        new
                        {
                            Id = "n2",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 4, 2, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Source = "Digest",
                            Title = "Another story placeholder"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.Profile.PlatformProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "You",
                            Email = "you@example.com"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.Profile.PlatformUserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DigestEmail")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DigestEmail = true,
                            Theme = "system"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.SavedItems.SavedItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("SavedItems");

                    b.HasData(
                        new
                        {
                            Id = "sv1",
                            Kind = "article",
                            SavedAt = new DateTimeOffset(new DateTime(2026, 4, 3, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Saved article (placeholder)"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.SideLearning.SideLearningTopic", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("SideLearningTopics");

                    b.HasData(
                        new
                        {
                            Id = "s1",
                            ProgressPercent = 40,
                            Title = "Foundations"
                        },
                        new
                        {
                            Id = "s2",
                            ProgressPercent = 10,
                            Title = "Applied practice"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.WorkflowRuns.WorkflowRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TemporalWorkflowId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WorkflowRuns");

                    b.HasData(
                        new
                        {
                            Id = "wr1",
                            Name = "News intelligence",
                            Status = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "wr2",
                            Name = "Side learning enrichment",
                            Status = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.ExplicitUserProfile", b =>
                {
                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryConsolidationRun", b =>
                {
                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryEmbedding", b =>
                {
                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryItem", "MemoryItem")
                        .WithMany()
                        .HasForeignKey("MemoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MemoryItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryEvent", b =>
                {
                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryEvidence", b =>
                {
                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryEvent", "SourceEvent")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Platform.Domain.Features.Memory.Entities.SemanticMemory", "SemanticMemory")
                        .WithMany()
                        .HasForeignKey("SemanticMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SemanticMemory");

                    b.Navigation("SourceEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryItem", b =>
                {
                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryRelationship", b =>
                {
                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.MemoryReviewQueueItem", b =>
                {
                    b.HasOne("Platform.Domain.Features.Memory.Entities.ProceduralRule", "ApprovedProceduralRule")
                        .WithMany()
                        .HasForeignKey("ApprovedProceduralRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Platform.Domain.Features.Memory.Entities.SemanticMemory", "ApprovedSemanticMemory")
                        .WithMany()
                        .HasForeignKey("ApprovedSemanticMemoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedProceduralRule");

                    b.Navigation("ApprovedSemanticMemory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.ProceduralRule", b =>
                {
                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.Entities.SemanticMemory", b =>
                {
                    b.HasOne("Platform.Domain.Features.Memory.Entities.MemoryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
