// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.Infrastructure.Persistence;

#nullable disable

namespace Platform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260424063351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.Domain.Features.Dashboard.StatsSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatsSnapshots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Json = "{\"tiles\":[{\"label\":\"Sessions Completed\",\"value\":24,\"unit\":\"\",\"color\":\"var(--accent)\",\"sub\":\"+3 this week\"},{\"label\":\"Articles Read\",\"value\":187,\"unit\":\"\",\"color\":\"var(--accent)\",\"sub\":\"+12 this week\"},{\"label\":\"Saved Items\",\"value\":43,\"unit\":\"\",\"color\":\"rgba(232,237,248,0.45)\",\"sub\":\"5 added recently\"},{\"label\":\"Day Streak\",\"value\":12,\"unit\":\"d\",\"color\":\"#34d399\",\"sub\":\"Personal best: 18d\"},{\"label\":\"Avg Session Length\",\"value\":38,\"unit\":\"min\",\"color\":\"var(--accent)\",\"sub\":\"Target: 45 min\"},{\"label\":\"Topics Explored\",\"value\":9,\"unit\":\"\",\"color\":\"#a78bfa\",\"sub\":\"3 in progress\"},{\"label\":\"Knowledge Score\",\"value\":94,\"unit\":\"%\",\"color\":\"#34d399\",\"sub\":\"Top 8% of users\"},{\"label\":\"Hours Learned\",\"value\":41,\"unit\":\"h\",\"color\":\"#fbbf24\",\"sub\":\"This month\"}],\"progress\":[{\"label\":\"Weekly Learning Goal\",\"value\":68,\"color\":\"var(--accent)\"},{\"label\":\"AI Ethics Mastery\",\"value\":82,\"color\":\"var(--accent)\"},{\"label\":\"Reading Streak\",\"value\":45,\"color\":\"#34d399\"},{\"label\":\"Profile Completion\",\"value\":91,\"color\":\"#a78bfa\"}],\"activity\":[{\"day\":\"Mon\",\"sessions\":2},{\"day\":\"Tue\",\"sessions\":1},{\"day\":\"Wed\",\"sessions\":3},{\"day\":\"Thu\",\"sessions\":0},{\"day\":\"Fri\",\"sessions\":2},{\"day\":\"Sat\",\"sessions\":1},{\"day\":\"Sun\",\"sessions\":2}]}"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.HumanInput.InputNeededItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Urgent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("InputNeededItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "How would you rate the difficulty and quality of your last session? This helps calibrate future recommendations.",
                            Text = "Rate your last AI Ethics session",
                            Type = "Rating",
                            Urgent = true
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Detected reading patterns suggesting interest in Quantum Computing. Add it to your interest profile?",
                            Text = "Confirm new interest: Quantum Computing?",
                            Type = "Confirm",
                            Urgent = false
                        },
                        new
                        {
                            Id = 3,
                            Detail = "You have completed your current track. Select a new area to explore from your recommended topics.",
                            Text = "Choose your next learning topic",
                            Type = "Choose",
                            Urgent = false
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.Memory.MemoryInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MemoryInsights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Confirmed = true,
                            Content = "You consistently engage with AI governance and regulation content over the past 6 weeks.",
                            Label = "Recurring Interest",
                            Strength = 94
                        },
                        new
                        {
                            Id = 2,
                            Confirmed = true,
                            Content = "You prefer structured sessions under 60 minutes, with hands-on exercises.",
                            Label = "Learning Pattern",
                            Strength = 87
                        },
                        new
                        {
                            Id = 3,
                            Confirmed = false,
                            Content = "Your reading behavior suggests growing interest in hardware-level AI acceleration.",
                            Label = "Emerging Trend",
                            Strength = 61
                        },
                        new
                        {
                            Id = 4,
                            Confirmed = false,
                            Content = "Foundational probability and statistics appear underrepresented in your learning history.",
                            Label = "Knowledge Gap",
                            Strength = 78
                        },
                        new
                        {
                            Id = 5,
                            Confirmed = false,
                            Content = "Based on your interests, a learning path toward AI Safety Research would match your profile well.",
                            Label = "Recommended Path",
                            Strength = 82
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.News.NewsItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("NewsItems");

                    b.HasData(
                        new
                        {
                            Id = "n1",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 4, 2, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Source = "Wire",
                            Title = "Sample headline (placeholder)"
                        },
                        new
                        {
                            Id = "n2",
                            PublishedAt = new DateTimeOffset(new DateTime(2026, 4, 2, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Source = "Digest",
                            Title = "Another story placeholder"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.Profile.PlatformProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "You",
                            Email = "you@example.com"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.Profile.PlatformUserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DigestEmail")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DigestEmail = true,
                            Theme = "system"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.SavedItems.SavedItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("SavedItems");

                    b.HasData(
                        new
                        {
                            Id = "sv1",
                            Kind = "article",
                            SavedAt = new DateTimeOffset(new DateTime(2026, 4, 3, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Title = "Saved article (placeholder)"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.SideLearning.SideLearningTopic", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("SideLearningTopics");

                    b.HasData(
                        new
                        {
                            Id = "s1",
                            ProgressPercent = 40,
                            Title = "Foundations"
                        },
                        new
                        {
                            Id = "s2",
                            ProgressPercent = 10,
                            Title = "Applied practice"
                        });
                });

            modelBuilder.Entity("Platform.Domain.Features.WorkflowRuns.WorkflowRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TemporalWorkflowId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WorkflowRuns");

                    b.HasData(
                        new
                        {
                            Id = "wr1",
                            Name = "News intelligence",
                            Status = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "wr2",
                            Name = "Side learning enrichment",
                            Status = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
